django1/src/blog/urls.py
'''
Created on 2019. 2. 9.

@author: Administrator
'''
from .views import *
from django.urls import path

app_name = 'blog'

urlpatterns = [
    #뷰클래스 등록 시 뷰클래스.as_view()로 등록
    path('', Index.as_view(), name='index'),
    #DetailView 클래스는 객체를 추출하기 위해 'pk' 매개변수를 사용함
    #127.0.0.1:8000/blog/글번호/
    path('<int:pk>/', Detail.as_view(), name='detail'),
    #127.0.0.1:8000/blog/posting/
    path('posting/', Posting.as_view(), name='posting')
    ]







django1/src/customlogin/urls.py
'''
Created on 2019. 1. 27.

@author: Administrator
'''
from django.urls import path
from .views import *

app_name = 'cl'
#기본주소 : 127.0.0.1:8000/cl/
urlpatterns = [
    #127.0.0.1:8000/cl/signup/
    path('signup/',signup, name='signup'),
    #127.0.0.1:8000/cl/signin/
    path('signin/',signin, name='signin'),
    #127.0.0.1:8000/cl/signout/
    path('signout/',signout,name='signout'),
    ]












django1/src/django1/urls.py
from django.contrib import admin
from django.urls import path, include
#bookmark/views.py 의 index, booklist함수 임포트
from bookmark.views import index, booklist, getbook
#from bookmark.views import * : 해당파일에 들어있는 모든 변수,함수,클래스 임포트

#url.py : 웹클라이언트의 요청을 분석해 특정한 뷰를 호출하는 역할
#urlpatterns : URL과 뷰함수를 등록 및 관리하는 변수
#리스트 형태로 저장. URL 등록 시 path함수를 통해 urlpatterns의 요소로 추가
#path(URL주소(문자열), 호출할 뷰함수/클래스 이름)

#기본 주소 : 127.0.0.1:8000
urlpatterns = [
    #웹 클라이언트가 127.0.0.1:8000/admin 으로 요청한 경우
    #관리자 사이트 뷰가 실행되도록 등록
    path('a1/', admin.site.urls),
    #웹 클라이언트가 127.0.0.1:8000/ 으로 요청한 경우 index 뷰함수 호출
    path('', index),
    path('booklist/', booklist),
    #127.0.0.1:8000/숫자값/ 으로 요청한 경우
    #getbook 뷰함수 호출. bookid 매개변수에 숫자값을 대입
    #URL에서 매개변수로 사용할 값을 분리하는 방법 : <값의타입:매개변수이름>
    path('<int:bookid>/', getbook),
    #투표어플리케이션에 사용할 하위 URLConf 등록
    #웹 클라이언트가 127.0.0.1:8000/vote/로 시작하는 모든 요청을
    #vote폴더에 있는 urls.py에 등록된 urlpatterns로 처리하도록 등록
    path('vote/', include('vote.urls')),
    #127.0.0.1:8000/cl/로 시작하는 모든 요청을 customlogin/urls.py에
    #넘겨줌
    path('cl/', include('customlogin.urls')),
    #127.0.0.1:8000/blog로 시작하는 모든요청을 blog/urls.py로 처리
    path('blog/', include('blog.urls') ),
    #social_django 어플리케이션의 하위 URLConf 등록
    path('auth/', include('social_django.urls',
                          namespace = 'social' ))
]

#미디어파일을 저장 및 요청처리 하기 위한 설정

#setting.py에 설정된 변수를 가져오기 위해 임포트
from django.conf import settings
#MEDIA_URL과 MEDIA_ROOT를 연결하기 위한 함수
from django.conf.urls.static import static

#파일 요청 URL과 실제 저장된 파일 경로를 매칭
urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)















django1/src/vote/urls.py
'''
Created on 2019. 1. 20.

@author: Administrator
'''
#하위 URLConf.
#app_name : 하위 URLConf 파일의 등록된 URL들의 그룹명
#urlpatterns : URL과 뷰함수를 리스트형태로 등록하는 변수
from django.urls import path
from .views import *
app_name = 'vote'
#기본 주소 : 127.0.0.1:8000/vote/
urlpatterns = [
    #웹 클라이언트가 127.0.0.1:8000/vote/ 요청 시 index 뷰함수 호출
    #name : 해당 URL, 뷰함수 등록에 대해서 별칭을 지정
    path('',index, name='index'),
    #127.0.0.1:8000/vote/숫자/
    path('<int:q_id>/', detail, name='detail'),
    path('vote/', vote, name='vote'),
    path('result/<int:q_id>/', result, name='result'),
    #127.0.0.1:8000/vote/qr
    path('qr/',qregister, name='qr' ),
    #127.0.0.1:8000/vote/qu/Question객체의id값
    path('qu/<int:q_id>/',qupdate, name='qu'),
    #127.0.0.1:8000/vote/qd/Question객체의id값
    path('qd/<int:q_id>/', qdelete, name='qd'),
    #127.0.0.1:8000/vote/cr/
    path('cr/', cregister, name='cr'),
    #127.0.0.1:8000/vote/cu/Choice객체id값
    path('cu/<int:c_id>/', cupdate, name='cu'),
    path('cd/<int:c_id>/', cdelete, name='cd'),
    ]
 












django1/src/blog/models.py
from django.db import models
#글쓴이를 외래키로 지정하기 위해 임포트
from django.contrib.auth.models import User

#카테고리
#카테고리 이름
class PostType(models.Model):
    name = models.CharField('카테고리', max_length=20)
    def __str__(self):
        return self.name
#글 정보
#제목, 글쓴이-외래키, 글내용, 작성일, 카테고리-외래키
class Post(models.Model):
    category = models.ForeignKey(PostType,
                                 on_delete=models.CASCADE)
    headline = models.CharField('제목',max_length=200)
    author = models.ForeignKey(User, 
                               on_delete=models.PROTECT)
    #TextField : 글자수 제한이 없는 문자열 저장공간
    #default 외에 XXXField에서 사용할 수 있는 공통 매개변수
    #null(기본값 False)  : True값을 저장한 경우, 데이터베이스에 객체 저장 시
    #            해당 변수값이 비어있어도 생성되도록 허용
    #blank(기본값 False) : True값을 저장한 경우, 폼객체를 통한 사용자 입력공
    #     간(<input>) 제공 시, 해당 변수의 입력공간을 빈칸으로 허용
    content = models.TextField('내용', null = True, blank=True)
    
    #auto_now_add(DateTimeField, DateField만 사용가능)
    #객체 생성 시, 서버 기준의 날짜/시간이 자동으로 저장되도록 설정하는 매개변수 
    pub_date = models.DateTimeField('작성일',auto_now_add=True)
    class Meta:
        #pub_date 변수에 저장된 값을 내림차순으로 정렬
        #-> 최신글 순으로 정렬
        ordering = ['-pub_date']
#글에 포함된 이미지 정보
#글-외래키, 이미지파일
#ImageField : 이미지파일을 저장하는 공간
#ImageField를 사용할려면 Pillow 모듈이 설치되있어야 함
#Pillow 모듈 : 파이썬에서 이미지처리할 때 사용하는 대표적인 모듈
#pip install Pillow
class PostImage(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #upload_to : 실제 파일이 저장되는 경로를 지정하는 매개변수
    #서버기준의 날짜데이터를 포함시킬 수 있음
    #%Y : 객체저장될때 서버기준의 년도
    #%m : 서버기준의 달
    #%d : 서버기준의 일
    #이미지 저장 시, images/년/월/일 폴더에 이미지파일이 저장
    image = models.ImageField('이미지파일',
                              upload_to='images/%Y/%m/%d')
#글에 포함된 첨부파일 정보
#글-외래키, 파일
class PostFile(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #FileField : 파일 데이터를 저장하는 공간
    file = models.FileField('첨부파일',
                            upload_to='files/%Y/%m/%d')







django1/src/blog/forms.py
'''
Created on 2019. 2. 9.

@author: Administrator
'''
from .models import Post
from django import forms

#글쓰기에 사용할 폼클래스 - 모델폼클래스 상속
class PostForm(forms.ModelForm):
    #사용자가 첨부파일, 이미지를 업로드할 수 있도록 커스텀 입력양식 생성
    #required=False : 해당<input>을 사용자가 필수로 입력하지 않아도되는
    #                 설정
    #첨부파일을 꼭 업로드하지않아도 되는 설정
    #ClearableFileInput : <input type='file'> 형태의 입력공간에
    #   파일관련 추가설정을 할 수 있는 위젯
    #multiple : 하나의 입력공간에 여러개의 파일을 업로드할 수 있도록 허용 
    files = forms.FileField(required=False,
    widget=forms.ClearableFileInput(attrs={'multiple':True}))
    
    images = forms.ImageField(required=False,
    widget=forms.ClearableFileInput(attrs={'multiple':True}))
    
    class Meta:
        model = Post
        fields = ['category','headline','content']











django1/src/blog/views.py
from django.shortcuts import render

#제네릭뷰 : 장고에서 제공하는 여러가지 뷰 기능을 구현한 클래스
#ListView : 특정 모델클래스의 객체 목록을 다루는 기능이 구현된 뷰
#DetailView : 특정 모델클래스의 객체 1개를 다루는 기능이 구현
#FormView : 특정 폼클래스를 다루는 기능이 구현
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from blog.models import Post, PostFile, PostImage
from blog.forms import PostForm
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse


#index : 글목록이 뜨는 메인페이지
class Index(ListView):
    #해당 뷰가 사용할 html 파일의 경로
    template_name='blog/index.html'
    #리스트로 뽑을 모델클래스
    model = Post
    #템플릿에게 객체리스트를 넘겨줄 때 사용할 키값
    context_object_name='list'
    #한페이지에 최대 몇개의 객체가 보여질지 설정
    paginate_by = 5
#detail : 글 상세보기 페이지
class Detail(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name ='obj'

from django.contrib.auth.mixins import LoginRequiredMixin
#posting : 글쓰기 페이지
class Posting(LoginRequiredMixin ,FormView):
    template_name = 'blog/posting.html'
    #연동할 폼클래스 저장
    form_class = PostForm
    context_object_name = 'f'
    
    #is_valid()함수가 True를 반환한 뒤의 처리를 form_valid()함수를
    #오버라이딩해서 작성
    def form_valid(self, form):
        #매개변수 form : is_valid()함수를 통과한 PostForm객체
        #PostForm객체를 바탕으로 Post객체 저장
        #글쓴이(author) 변수가 비어있으므로, 데이터베이스에 저장하지않음
        p = form.save(commit=False)#p : Post 객체
        #request.user : 요청한 클라이언트의 로그인정보(User 모델클래스 객체)
        p.author = self.request.user
        p.save() #Post 객체가 데이터베이스에 저장됨
        
        #클라이언트가 보낸 첨부파일, 이미지파일을 바탕으로 PostFile,
        #PostImage객체 생성 및 저장
        #request.FILES : 클라이언트가 서버로 보낸 파일정보를 관리하는 변수
        
        #PostFile 객체를 생성
        for f in self.request.FILES.getlist('files'):
            #f : 파일 정보
            pf = PostFile() #새로운 PostFile 모델클래스의 객체 생성
            pf.file= f
            pf.post= p
            pf.save() #데이터베이스에 새로운 PostFile 객체가 저장됨
        
        #PostImage 객체를 생성
        for i in self.request.FILES.getlist('images'):
            #i : 이미지 정보
            pi = PostImage()
            pi.post = p
            pi.image = i
            pi.save()
            
        #완성된 글페이지로 URL이동
        return HttpResponseRedirect( 
            reverse('blog:detail', args=(p.id,) ) )
    
    
    
    
    
    
    
    




django1/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>블로그</title>
</head>
<body>
<!-- 배너 -->
<h3> 나만의 홈페이지 </h3>
<!-- 어플리케이션 바로가기 링크 -->
<a href="/">북마크</a>
<a href="{% url 'vote:index' %}">설문조사</a>
<a href="{% url 'blog:index' %}">블로그</a>
<br>
<!-- 로그인/비로그인 처리 : 클라이언트의 로그인정보가 user변수에 들어있음
user.is_authenticated : 사용자가 현재 로그인이 되어있는지 
                        True(로그인),False(비로그인)반환-->
{% if user.is_authenticated %}
	<!-- 로그인이 된 경우 -->
	<p> {{ user.last_name }} {{ user.first_name }}
	님 환영합니다! <a href="{% url 'cl:signout'%}">로그아웃</a> </p>
{% else %}
	<!-- 로그인이 안된경우  -->
	<a href="{% url 'cl:signin' %}">로그인</a>
	<a href="{% url 'cl:signup' %}">회원가입</a>
{% endif %}
<hr>
<!-- 수정할 수 있는 공간 
block tag : 해당 html을 다른 html이 확장할 때 수정할 수 있는 공간을 설정
다른 html이 블록을 수정하고싶은 경우 블록이름과 동일한 블록을 생성해 HTML코드
작성-->
{% block content%}

{% endblock %}
<!--  -->
</body>
</html>








django1/src/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
<!-- obj : Post 모델 객체 1개 -->
{% block content %}
<h3>[ {{ obj.category }} ]{{ obj.headline }}</h3>
<p> {{ obj.author }} / {{ obj.pub_date }} </p>
<!-- Post 객체와 연결된 PostImage, PostFile 객체 추출 -->
{% for f in obj.postfile_set.all %}
	<a href="{{ f.file.url }}" download>첨부파일</a>
	<br>
{% endfor %}
{% for i in obj.postimage_set.all %}
	<img src="{{ i.image.url }}" width="30%">
	<br>
{% endfor %}
<pre>{{obj.content}}</pre>
{% endblock %}





django1/src/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
<!-- extends : 다른 HTML을 확장하겠다는 선언. 
확장할 HTML에 등록된 블록만 수정가능 -->
<!-- list : Post 객체 리스트 
page_obj : ListView 클래스가 넘겨주는 페이지 정보
page_obj.has_previous : 이전 페이지가 존재하면 True, 없으면 False
page_obj.has_next : 다음 페이지가 존재하면 True, 없으면 False 
page_obj.next_page_number : 현재페이지 기준 다음페이지의 번호 
page_obj.previous_page_number : 현재페이지 기준 이전페이지의 번호-->
{% block content %}
<!-- 이전페이지, 다음페이지 버튼 생성 -->
{% if page_obj.has_previous %}
	<a href="?page={{page_obj.previous_page_number}}">
	    이전페이지</a>
{% endif %}

{% if page_obj.has_next %}
	<a href="?page={{page_obj.next_page_number}}">다음페이지</a>
{% endif %}

<table width = "90%">
	<tr>
		<th>글번호</th>
		<th>카테고리</th>
		<th>제목</th>
		<th>작성자</th>
		<th>작성일</th>
	</tr>
	{% for post in list %}
		<tr>
			<th>{{ post.id }}</th>
			<th>{{ post.category }}</th>
			<th>{{ post.headline }}</th>
			<th>{{ post.author }}</th>
			<th>{{ post.pub_date }}</th>
		</tr>
	{% endfor %}
</table>

{% endblock %}








django1/src/blog/templates/blog/posting.html
{% extends 'blog/base.html' %}
<!-- form : PostForm 폼클래스 객체 -->
{% block content %}
<h3>글 쓰기</h3>
<!-- enctype="multipart/form-data" : 해당 폼으로 파일데이터를
서버에 전달할수 있도록 설정 -->
<form action="" method="post" 
      enctype="multipart/form-data">
      {% csrf_token %}
      <table>
      	{{ form.as_table }}
      </table>
      <input type="submit" value ="갱신">
</form>

<a href="{% url 'blog:index'%}">메인페이지 돌아가기</a>
{% endblock %}
